[kijanikiosk]
api ansible_host=10.50.121.98
payments ansible_host=10.50.121.16
logs ansible_host=10.50.121.194

[kijanikiosk:vars]
ansible_user=ubuntu
ansible_ssh_private_key_file=~/.ssh/multipass_id_rsa
ansible_python_interpreter=/usr/bin/python3
ansible_ssh_common_args='-o StrictHostKeyChecking=no'
